data_path: "/home/sahragard/datasets/common_voice_13"
txt_path: ./vctk/txt
use_hf: True
hf_dataset_path: "/home/sahragard/datasets/common_voice_13"
hf_dataset_split: vc_100
spk_info_path: ./vctk/speaker-info.txt
output_path: ./base_data
cpc_path: ./cpc
sampling_rate: 16000
top_db: 60
n_mels: 80
n_fft: 400
n_shift: 160
win_length: 400
window: hann
fmin: 80
fmax: 7600
s2s_portion: 0.1
eval_spks: 10 # we can specify the test speakers
num_samples: 300 # number of sample pairs

